//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class CameraMsgMsg : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/CameraMsg";
        public override string RosMessageName => k_RosMessageName;

        //  Custom message to hold the list of Image objects from the
        //  cameras connected.
        // 
        //  This message holds a list of sensor_msgs/Image objects that are
        //  independently collected from different camera sensors.
        public Sensor.ImageMsg[] images;
        //  Image data read from cameras.

        public CameraMsgMsg()
        {
            this.images = new Sensor.ImageMsg[0];
        }

        public CameraMsgMsg(Sensor.ImageMsg[] images)
        {
            this.images = images;
        }

        public static CameraMsgMsg Deserialize(MessageDeserializer deserializer) => new CameraMsgMsg(deserializer);

        private CameraMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.images, Sensor.ImageMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.images);
            serializer.Write(this.images);
        }

        public override string ToString()
        {
            return "CameraMsgMsg: " +
            "\nimages: " + System.String.Join(", ", images.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
