//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class EvoSensorMsg : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/EvoSensor";
        public override string RosMessageName => k_RosMessageName;

        //  Custom message to combine different sensor messages.
        // 
        //  This message holds a list of sensor_msgs/Image objects that are
        //  independently collected from different camera sensors. And an
        //  array of distance values read from the LiDAR sensor.
        public Sensor.ImageMsg[] images;
        //  Image data read from cameras.
        public float[] lidar_data;
        //  LiDAR distance data read from LiDAR sensor.

        public EvoSensorMsg()
        {
            this.images = new Sensor.ImageMsg[0];
            this.lidar_data = new float[0];
        }

        public EvoSensorMsg(Sensor.ImageMsg[] images, float[] lidar_data)
        {
            this.images = images;
            this.lidar_data = lidar_data;
        }

        public static EvoSensorMsg Deserialize(MessageDeserializer deserializer) => new EvoSensorMsg(deserializer);

        private EvoSensorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.images, Sensor.ImageMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.lidar_data, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.images);
            serializer.Write(this.images);
            serializer.WriteLength(this.lidar_data);
            serializer.Write(this.lidar_data);
        }

        public override string ToString()
        {
            return "EvoSensorMsg: " +
            "\nimages: " + System.String.Join(", ", images.ToList()) +
            "\nlidar_data: " + System.String.Join(", ", lidar_data.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
