//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class InferResultsMsg : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/InferResults";
        public override string RosMessageName => k_RosMessageName;

        //  Custom message with one inference result details.
        // 
        //  This message is used to communicate the inference results.
        public int class_label;
        //  Identifier for a particular class.
        public float class_prob;
        //  Predicted probability value for the class.
        //  Bounding box localization information.
        public float x_min;
        public float y_min;
        public float x_max;
        public float y_max;

        public InferResultsMsg()
        {
            this.class_label = 0;
            this.class_prob = 0.0f;
            this.x_min = 0.0f;
            this.y_min = 0.0f;
            this.x_max = 0.0f;
            this.y_max = 0.0f;
        }

        public InferResultsMsg(int class_label, float class_prob, float x_min, float y_min, float x_max, float y_max)
        {
            this.class_label = class_label;
            this.class_prob = class_prob;
            this.x_min = x_min;
            this.y_min = y_min;
            this.x_max = x_max;
            this.y_max = y_max;
        }

        public static InferResultsMsg Deserialize(MessageDeserializer deserializer) => new InferResultsMsg(deserializer);

        private InferResultsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.class_label);
            deserializer.Read(out this.class_prob);
            deserializer.Read(out this.x_min);
            deserializer.Read(out this.y_min);
            deserializer.Read(out this.x_max);
            deserializer.Read(out this.y_max);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.class_label);
            serializer.Write(this.class_prob);
            serializer.Write(this.x_min);
            serializer.Write(this.y_min);
            serializer.Write(this.x_max);
            serializer.Write(this.y_max);
        }

        public override string ToString()
        {
            return "InferResultsMsg: " +
            "\nclass_label: " + class_label.ToString() +
            "\nclass_prob: " + class_prob.ToString() +
            "\nx_min: " + x_min.ToString() +
            "\ny_min: " + y_min.ToString() +
            "\nx_max: " + x_max.ToString() +
            "\ny_max: " + y_max.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
