//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class InferResultsArrayMsg : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/InferResultsArray";
        public override string RosMessageName => k_RosMessageName;

        //  Custom message with an array of inference result and corresponding state details.
        // 
        //  This message is used to communicate the inference results and the corresponding
        //  state input (images) on which the inference was run on. 
        public InferResultsMsg[] results;
        //  Array of inference results.
        public Sensor.ImageMsg[] images;
        //  Array of input images on which the inference was run. 

        public InferResultsArrayMsg()
        {
            this.results = new InferResultsMsg[0];
            this.images = new Sensor.ImageMsg[0];
        }

        public InferResultsArrayMsg(InferResultsMsg[] results, Sensor.ImageMsg[] images)
        {
            this.results = results;
            this.images = images;
        }

        public static InferResultsArrayMsg Deserialize(MessageDeserializer deserializer) => new InferResultsArrayMsg(deserializer);

        private InferResultsArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.results, InferResultsMsg.Deserialize, deserializer.ReadLength());
            deserializer.Read(out this.images, Sensor.ImageMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
            serializer.WriteLength(this.images);
            serializer.Write(this.images);
        }

        public override string ToString()
        {
            return "InferResultsArrayMsg: " +
            "\nresults: " + System.String.Join(", ", results.ToList()) +
            "\nimages: " + System.String.Join(", ", images.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
