//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SoftwareUpdatePctMsg : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SoftwareUpdatePct";
        public override string RosMessageName => k_RosMessageName;

        //  Custom message with software update progress details.
        // 
        //  This message is used to send the software update progress
        //  percentage and the corresponding stage in the update process.
        public float update_pct;
        //  [0-100] value to indicate the software update
        //  progress percentage 
        public string status;
        //  Value indicating the stage of the update process.
        //  Ex: checking, downloading, installing, etc,.

        public SoftwareUpdatePctMsg()
        {
            this.update_pct = 0.0f;
            this.status = "";
        }

        public SoftwareUpdatePctMsg(float update_pct, string status)
        {
            this.update_pct = update_pct;
            this.status = status;
        }

        public static SoftwareUpdatePctMsg Deserialize(MessageDeserializer deserializer) => new SoftwareUpdatePctMsg(deserializer);

        private SoftwareUpdatePctMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.update_pct);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.update_pct);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "SoftwareUpdatePctMsg: " +
            "\nupdate_pct: " + update_pct.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
