//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class ActiveStateSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/ActiveStateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Vehicle mode (manual, automatic, calibration) that is to be activated on the device
        //  after deactivating and resetting the current active mode.
        public sbyte state;

        public ActiveStateSrvRequest()
        {
            this.state = 0;
        }

        public ActiveStateSrvRequest(sbyte state)
        {
            this.state = state;
        }

        public static ActiveStateSrvRequest Deserialize(MessageDeserializer deserializer) => new ActiveStateSrvRequest(deserializer);

        private ActiveStateSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ActiveStateSrvRequest: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
