//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class BeginSoftwareUpdateSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/BeginSoftwareUpdateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Time to sleep in seconds after software update before rebooting the device.
        public int sleep_time_before_reboot;

        public BeginSoftwareUpdateSrvRequest()
        {
            this.sleep_time_before_reboot = 0;
        }

        public BeginSoftwareUpdateSrvRequest(int sleep_time_before_reboot)
        {
            this.sleep_time_before_reboot = sleep_time_before_reboot;
        }

        public static BeginSoftwareUpdateSrvRequest Deserialize(MessageDeserializer deserializer) => new BeginSoftwareUpdateSrvRequest(deserializer);

        private BeginSoftwareUpdateSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.sleep_time_before_reboot);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.sleep_time_before_reboot);
        }

        public override string ToString()
        {
            return "BeginSoftwareUpdateSrvRequest: " +
            "\nsleep_time_before_reboot: " + sleep_time_before_reboot.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
