//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class ConsoleModelActionSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/ConsoleModelActionSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Path to the directory where the model files are present.
        public string model_path;
        //  action=1 (For upload the model) & action=0 for deleting the model.
        public int action;

        public ConsoleModelActionSrvRequest()
        {
            this.model_path = "";
            this.action = 0;
        }

        public ConsoleModelActionSrvRequest(string model_path, int action)
        {
            this.model_path = model_path;
            this.action = action;
        }

        public static ConsoleModelActionSrvRequest Deserialize(MessageDeserializer deserializer) => new ConsoleModelActionSrvRequest(deserializer);

        private ConsoleModelActionSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_path);
            deserializer.Read(out this.action);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_path);
            serializer.Write(this.action);
        }

        public override string ToString()
        {
            return "ConsoleModelActionSrvRequest: " +
            "\nmodel_path: " + model_path.ToString() +
            "\naction: " + action.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
