//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class ConsoleModelActionSrvResponse : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/ConsoleModelActionSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Details about the action execution status.
        public string status;

        public ConsoleModelActionSrvResponse()
        {
            this.status = "";
        }

        public ConsoleModelActionSrvResponse(string status)
        {
            this.status = status;
        }

        public static ConsoleModelActionSrvResponse Deserialize(MessageDeserializer deserializer) => new ConsoleModelActionSrvResponse(deserializer);

        private ConsoleModelActionSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "ConsoleModelActionSrvResponse: " +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
