//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class EnableStateSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/EnableStateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Activate/Deactivate the current mode(manual, automatic, calibration).
        public bool is_active;

        public EnableStateSrvRequest()
        {
            this.is_active = false;
        }

        public EnableStateSrvRequest(bool is_active)
        {
            this.is_active = is_active;
        }

        public static EnableStateSrvRequest Deserialize(MessageDeserializer deserializer) => new EnableStateSrvRequest(deserializer);

        private EnableStateSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_active);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_active);
        }

        public override string ToString()
        {
            return "EnableStateSrvRequest: " +
            "\nis_active: " + is_active.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
