//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class GetCalibrationSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/GetCalibrationSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Calibration type (steering/speed)
        public int cal_type;

        public GetCalibrationSrvRequest()
        {
            this.cal_type = 0;
        }

        public GetCalibrationSrvRequest(int cal_type)
        {
            this.cal_type = cal_type;
        }

        public static GetCalibrationSrvRequest Deserialize(MessageDeserializer deserializer) => new GetCalibrationSrvRequest(deserializer);

        private GetCalibrationSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cal_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cal_type);
        }

        public override string ToString()
        {
            return "GetCalibrationSrvRequest: " +
            "\ncal_type: " + cal_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
