//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class GetLedCtrlSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/GetLedCtrlSrv";
        public override string RosMessageName => k_RosMessageName;


        public GetLedCtrlSrvRequest()
        {
        }
        public static GetLedCtrlSrvRequest Deserialize(MessageDeserializer deserializer) => new GetLedCtrlSrvRequest(deserializer);

        private GetLedCtrlSrvRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetLedCtrlSrvRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
