//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class GetModelLoadingStatusSrvResponse : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/GetModelLoadingStatusSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Status to indicate model is loading or already loaded.
        public string model_loading_status;
        //  Error flag indicating successful/failed service call.
        public int error;

        public GetModelLoadingStatusSrvResponse()
        {
            this.model_loading_status = "";
            this.error = 0;
        }

        public GetModelLoadingStatusSrvResponse(string model_loading_status, int error)
        {
            this.model_loading_status = model_loading_status;
            this.error = error;
        }

        public static GetModelLoadingStatusSrvResponse Deserialize(MessageDeserializer deserializer) => new GetModelLoadingStatusSrvResponse(deserializer);

        private GetModelLoadingStatusSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_loading_status);
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_loading_status);
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "GetModelLoadingStatusSrvResponse: " +
            "\nmodel_loading_status: " + model_loading_status.ToString() +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
