//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class InferenceStateSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/InferenceStateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Flag to start/stop inference.
        public sbyte start;
        //  Identifier of a particular type of inference (Ex: reinforcement learning).
        public sbyte task_type;

        public InferenceStateSrvRequest()
        {
            this.start = 0;
            this.task_type = 0;
        }

        public InferenceStateSrvRequest(sbyte start, sbyte task_type)
        {
            this.start = start;
            this.task_type = task_type;
        }

        public static InferenceStateSrvRequest Deserialize(MessageDeserializer deserializer) => new InferenceStateSrvRequest(deserializer);

        private InferenceStateSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.start);
            deserializer.Read(out this.task_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.start);
            serializer.Write(this.task_type);
        }

        public override string ToString()
        {
            return "InferenceStateSrvRequest: " +
            "\nstart: " + start.ToString() +
            "\ntask_type: " + task_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
