//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class LoadModelSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/LoadModelSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Path where the interemediate representation xml file for the model is present.
        public string artifact_path;
        //  Identifier of a particular type of inference (Ex: reinforcement learning).
        public sbyte task_type;
        //  Identifier of a particular type of preprocessing (Ex: grey scale + resize).
        public sbyte pre_process_type;
        //  Identifier for the action space type used by the model during training.
        public sbyte action_space_type;

        public LoadModelSrvRequest()
        {
            this.artifact_path = "";
            this.task_type = 0;
            this.pre_process_type = 0;
            this.action_space_type = 0;
        }

        public LoadModelSrvRequest(string artifact_path, sbyte task_type, sbyte pre_process_type, sbyte action_space_type)
        {
            this.artifact_path = artifact_path;
            this.task_type = task_type;
            this.pre_process_type = pre_process_type;
            this.action_space_type = action_space_type;
        }

        public static LoadModelSrvRequest Deserialize(MessageDeserializer deserializer) => new LoadModelSrvRequest(deserializer);

        private LoadModelSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.artifact_path);
            deserializer.Read(out this.task_type);
            deserializer.Read(out this.pre_process_type);
            deserializer.Read(out this.action_space_type);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.artifact_path);
            serializer.Write(this.task_type);
            serializer.Write(this.pre_process_type);
            serializer.Write(this.action_space_type);
        }

        public override string ToString()
        {
            return "LoadModelSrvRequest: " +
            "\nartifact_path: " + artifact_path.ToString() +
            "\ntask_type: " + task_type.ToString() +
            "\npre_process_type: " + pre_process_type.ToString() +
            "\naction_space_type: " + action_space_type.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
