//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class OTGLinkStateSrvResponse : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/OTGLinkStateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Flag to indicate if the device is connected using OTG cable.
        public bool link_state;

        public OTGLinkStateSrvResponse()
        {
            this.link_state = false;
        }

        public OTGLinkStateSrvResponse(bool link_state)
        {
            this.link_state = link_state;
        }

        public static OTGLinkStateSrvResponse Deserialize(MessageDeserializer deserializer) => new OTGLinkStateSrvResponse(deserializer);

        private OTGLinkStateSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.link_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.link_state);
        }

        public override string ToString()
        {
            return "OTGLinkStateSrvResponse: " +
            "\nlink_state: " + link_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
