//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SetStatusLedSolidSrvResponse : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SetStatusLedSolidSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Error flag indicating successful/failed service call.
        public int error;

        public SetStatusLedSolidSrvResponse()
        {
            this.error = 0;
        }

        public SetStatusLedSolidSrvResponse(int error)
        {
            this.error = error;
        }

        public static SetStatusLedSolidSrvResponse Deserialize(MessageDeserializer deserializer) => new SetStatusLedSolidSrvResponse(deserializer);

        private SetStatusLedSolidSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.error);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error);
        }

        public override string ToString()
        {
            return "SetStatusLedSolidSrvResponse: " +
            "\nerror: " + error.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
