//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SetStatusLedBlinkSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SetStatusLedBlinkSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Identifier for the status LED light by the side of the device.
        public int led_index;
        //  First color value to be set on the status LED.
        public string color1;
        //  Second color value to be set on the status LED.
        public string color2;
        //  Time in seconds to hold each color for the blink effect.
        public float delay;

        public SetStatusLedBlinkSrvRequest()
        {
            this.led_index = 0;
            this.color1 = "";
            this.color2 = "";
            this.delay = 0.0f;
        }

        public SetStatusLedBlinkSrvRequest(int led_index, string color1, string color2, float delay)
        {
            this.led_index = led_index;
            this.color1 = color1;
            this.color2 = color2;
            this.delay = delay;
        }

        public static SetStatusLedBlinkSrvRequest Deserialize(MessageDeserializer deserializer) => new SetStatusLedBlinkSrvRequest(deserializer);

        private SetStatusLedBlinkSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.led_index);
            deserializer.Read(out this.color1);
            deserializer.Read(out this.color2);
            deserializer.Read(out this.delay);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.led_index);
            serializer.Write(this.color1);
            serializer.Write(this.color2);
            serializer.Write(this.delay);
        }

        public override string ToString()
        {
            return "SetStatusLedBlinkSrvRequest: " +
            "\nled_index: " + led_index.ToString() +
            "\ncolor1: " + color1.ToString() +
            "\ncolor2: " + color2.ToString() +
            "\ndelay: " + delay.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
