//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SetStatusLedSolidSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SetStatusLedSolidSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Identifier for the status LED light by the side of the device.
        public int led_index;
        //  Color value to be set on the status LED.
        public string color;
        //  Least amount of time in seconds to hold the effect before
        //  waiting for next effect.
        public float hold;

        public SetStatusLedSolidSrvRequest()
        {
            this.led_index = 0;
            this.color = "";
            this.hold = 0.0f;
        }

        public SetStatusLedSolidSrvRequest(int led_index, string color, float hold)
        {
            this.led_index = led_index;
            this.color = color;
            this.hold = hold;
        }

        public static SetStatusLedSolidSrvRequest Deserialize(MessageDeserializer deserializer) => new SetStatusLedSolidSrvRequest(deserializer);

        private SetStatusLedSolidSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.led_index);
            deserializer.Read(out this.color);
            deserializer.Read(out this.hold);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.led_index);
            serializer.Write(this.color);
            serializer.Write(this.hold);
        }

        public override string ToString()
        {
            return "SetStatusLedSolidSrvRequest: " +
            "\nled_index: " + led_index.ToString() +
            "\ncolor: " + color.ToString() +
            "\nhold: " + hold.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
