//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SoftwareUpdateCheckSrvResponse : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SoftwareUpdateCheckSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Identifier with the current software update state details.
        public int software_update_state;

        public SoftwareUpdateCheckSrvResponse()
        {
            this.software_update_state = 0;
        }

        public SoftwareUpdateCheckSrvResponse(int software_update_state)
        {
            this.software_update_state = software_update_state;
        }

        public static SoftwareUpdateCheckSrvResponse Deserialize(MessageDeserializer deserializer) => new SoftwareUpdateCheckSrvResponse(deserializer);

        private SoftwareUpdateCheckSrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.software_update_state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.software_update_state);
        }

        public override string ToString()
        {
            return "SoftwareUpdateCheckSrvResponse: " +
            "\nsoftware_update_state: " + software_update_state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
