//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SoftwareUpdateStateSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SoftwareUpdateStateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Flag with request object.
        public bool request;

        public SoftwareUpdateStateSrvRequest()
        {
            this.request = false;
        }

        public SoftwareUpdateStateSrvRequest(bool request)
        {
            this.request = request;
        }

        public static SoftwareUpdateStateSrvRequest Deserialize(MessageDeserializer deserializer) => new SoftwareUpdateStateSrvRequest(deserializer);

        private SoftwareUpdateStateSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.request);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.request);
        }

        public override string ToString()
        {
            return "SoftwareUpdateStateSrvRequest: " +
            "\nrequest: " + request.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
