//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class SoftwareUpdateCheckSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/SoftwareUpdateCheckSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Flag to indicate if we should check for software update immediately.
        public int force_update_check;

        public SoftwareUpdateCheckSrvRequest()
        {
            this.force_update_check = 0;
        }

        public SoftwareUpdateCheckSrvRequest(int force_update_check)
        {
            this.force_update_check = force_update_check;
        }

        public static SoftwareUpdateCheckSrvRequest Deserialize(MessageDeserializer deserializer) => new SoftwareUpdateCheckSrvRequest(deserializer);

        private SoftwareUpdateCheckSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.force_update_check);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.force_update_check);
        }

        public override string ToString()
        {
            return "SoftwareUpdateCheckSrvRequest: " +
            "\nforce_update_check: " + force_update_check.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
