//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class USBFileSystemSubscribeSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/USBFileSystemSubscribeSrv";
        public override string RosMessageName => k_RosMessageName;

        //  File/folder to be added to the watchlist.
        public string file_name;
        //  Callback name that is will be triggered if the file/folder is found.
        public string callback_name;
        //  If set to True, notification will be sent for the callback only if the
        //  particular file is found.
        //  Else will be triggered irrespectively to indicate connection of USB drive.
        public bool verify_name_exists;

        public USBFileSystemSubscribeSrvRequest()
        {
            this.file_name = "";
            this.callback_name = "";
            this.verify_name_exists = false;
        }

        public USBFileSystemSubscribeSrvRequest(string file_name, string callback_name, bool verify_name_exists)
        {
            this.file_name = file_name;
            this.callback_name = callback_name;
            this.verify_name_exists = verify_name_exists;
        }

        public static USBFileSystemSubscribeSrvRequest Deserialize(MessageDeserializer deserializer) => new USBFileSystemSubscribeSrvRequest(deserializer);

        private USBFileSystemSubscribeSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.file_name);
            deserializer.Read(out this.callback_name);
            deserializer.Read(out this.verify_name_exists);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.file_name);
            serializer.Write(this.callback_name);
            serializer.Write(this.verify_name_exists);
        }

        public override string ToString()
        {
            return "USBFileSystemSubscribeSrvRequest: " +
            "\nfile_name: " + file_name.ToString() +
            "\ncallback_name: " + callback_name.ToString() +
            "\nverify_name_exists: " + verify_name_exists.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
