//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class VerifyModelReadySrvResponse : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/VerifyModelReadySrv";
        public override string RosMessageName => k_RosMessageName;

        //  True if the model is properly loaded/has checksum.txt in the model folder else False.
        public bool response_status;

        public VerifyModelReadySrvResponse()
        {
            this.response_status = false;
        }

        public VerifyModelReadySrvResponse(bool response_status)
        {
            this.response_status = response_status;
        }

        public static VerifyModelReadySrvResponse Deserialize(MessageDeserializer deserializer) => new VerifyModelReadySrvResponse(deserializer);

        private VerifyModelReadySrvResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.response_status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.response_status);
        }

        public override string ToString()
        {
            return "VerifyModelReadySrvResponse: " +
            "\nresponse_status: " + response_status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
