//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class VerifyModelReadySrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/VerifyModelReadySrv";
        public override string RosMessageName => k_RosMessageName;

        //  Model folder name in the install directory.
        public string model_name;

        public VerifyModelReadySrvRequest()
        {
            this.model_name = "";
        }

        public VerifyModelReadySrvRequest(string model_name)
        {
            this.model_name = model_name;
        }

        public static VerifyModelReadySrvRequest Deserialize(MessageDeserializer deserializer) => new VerifyModelReadySrvRequest(deserializer);

        private VerifyModelReadySrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.model_name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.model_name);
        }

        public override string ToString()
        {
            return "VerifyModelReadySrvRequest: " +
            "\nmodel_name: " + model_name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
