//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.DeepracerInterfacesPkg
{
    [Serializable]
    public class VideoStateSrvRequest : Message
    {
        public const string k_RosMessageName = "deepracer_interfaces_pkg/VideoStateSrv";
        public override string RosMessageName => k_RosMessageName;

        //  Flag to activate camera node and start publishing images.
        public sbyte activate_video;

        public VideoStateSrvRequest()
        {
            this.activate_video = 0;
        }

        public VideoStateSrvRequest(sbyte activate_video)
        {
            this.activate_video = activate_video;
        }

        public static VideoStateSrvRequest Deserialize(MessageDeserializer deserializer) => new VideoStateSrvRequest(deserializer);

        private VideoStateSrvRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.activate_video);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.activate_video);
        }

        public override string ToString()
        {
            return "VideoStateSrvRequest: " +
            "\nactivate_video: " + activate_video.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
